<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-06-14 10:33

$extensionPath = t3lib_extMgm::extPath('rdf_export');
$extensionClassesPath = t3lib_extMgm::extPath('rdf_export') . 'Classes/';
return array(
	'tx_rdfexport_columnmapper' => $extensionClassesPath . 'ColumnMapper.php',
	'tx_rdfexport_datastructureexporter' => $extensionClassesPath . 'DataStructureExporter.php',
	'tx_rdfexport_helper' => $extensionClassesPath . 'Helper.php',
	'tx_rdfexport_model_ontology' => $extensionClassesPath . 'Model/Ontology.php',
	'tx_rdfexport_model_ontology_class' => $extensionClassesPath . 'Model/Ontology/Class.php',
	'tx_rdfexport_model_ontology_classinstance' => $extensionClassesPath . 'Model/Ontology/ClassInstance.php',
	'tx_rdfexport_model_ontology_objectproperty' => $extensionClassesPath . 'Model/Ontology/ObjectProperty.php',
	'tx_rdfexport_model_ontology_property' => $extensionClassesPath . 'Model/Ontology/Property.php',
	'tx_rdfexport_columnmappertest' => $extensionPath . 'Tests/ColumnMapperTest.php',
	'tx_rdfexport_datastructureexportertest' => $extensionPath . 'Tests/DataStructureExporterTest.php',
	'tx_rdfexport_helpertest' => $extensionPath . 'Tests/HelperTest.php',
	'tx_rdfexport_module1' => $extensionPath . 'mod1/index.php',
);
?>